import type { Metadata } from 'next';
import Header from './layouts/Header';
import cx from 'classnames';
import { notoSans, notoSansKR } from './styles/fonts.ts';
import './styles/global.css';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={cx(notoSans.className, notoSansKR.className)}>
                <Header />
                {children}
            </body>
        </html>
    );
}
