import React from 'react';
import type { Metadata } from 'next';
import Header from './layouts/Header';
import cx from 'classnames';
import RecoilRootWrapper from '@/context/RecoilWrapper';
import './styles/global.css';
import ModalProvider from './components/Modal/provider';
import { notoSans, notoSansKR } from './styles/fonts';
import ReactQueryWrapper from './context/ReactQueryWrapper';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                id="next"
                className={cx(notoSans.className, notoSansKR.className)}
            >
                <ReactQueryWrapper>
                    <RecoilRootWrapper>
                        <Header />
                        {children}
                        <ModalProvider />
                    </RecoilRootWrapper>
                </ReactQueryWrapper>
            </body>
        </html>
    );
}
